--------- INSERT SCRIPTS TO INITIALIZE DATABASE GO HERE --------
INSERT INTO connection_types_gdma2(id, connection_class, name, select_get_tables, cast_column_for_search) VALUES (1, 'com.mysql.jdbc.Driver', 'MySQL (JDBC)', 'SHOW TABLES', 'CAST({0} AS CHAR)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (2,  'select table_schema||''.''||table_name as table_name from information_schema.tables where table_schema not in (''pg_catalog'', ''information_schema'') order by table_schema||''.''||table_name', 'org.postgresql.Driver', 'Postgres 9.6.2 JDBC', 'CAST({0} AS VARCHAR)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (3,  'SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE= ''U'' ORDER BY NAME', 'sun.jdbc.odbc.JdbcOdbcDriver', 'MS SQL Server (ODBC)', 'CAST({0} AS VARCHAR)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (4,  'select table_name as TABLE_NAME from user_tables', 'sun.jdbc.odbc.JdbcOdbcDriver', 'Oracle 8/9 (ODBC)', 'CAST({0} AS VARCHAR2)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (5,  'select table_name as TABLE_NAME from user_tables', 'oracle.jdbc.OracleDriver', 'Oracle 8/9 (JDBC)', 'CAST({0} AS VARCHA2)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (6,  'SELECT TABLENAME AS TABLE_NAME FROM DBC.TABLES ORDER BY TABLENAME', 'sun.jdbc.odbc.JdbcOdbcDriver', 'Teradata 8/9 (ODBC)', 'CAST({0} AS CHAR(255))');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (7, 'SELECT TABLENAME AS TABLE_NAME FROM DBC.TABLES ORDER BY TABLENAME where databasename = ''financial''', 'com.teradata.jdbc.TeraDriver', 'Teradata 8/9 (JDBC)', 'CAST({0} AS CHAR(255))');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (8,  'SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE=''U'' ORDER BY NAME', 'net.sourceforge.jtds.jdbc.Driver', 'MS SQL Server (JDBC)', 'CAST({0} AS VARCHAR)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (9,  'SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE=''V'' ORDER BY NAME', 'net.sourceforge.jtds.jdbc.Driver', 'MS SQL Server (JDBC)(Views)', 'CAST({0} AS VARCHAR)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (10,  'SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE IN (''U'', ''V'') ORDER BY NAME', 'net.sourceforge.jtds.jdbc.Driver', 'MS SQL Server (JDBC)(Both)', 'CAST({0} AS VARCHAR)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (11,  'SELECT TABLENAME AS TABLE_NAME FROM DBC.TABLES ORDER BY TABLENAME where databasename = ''gdma_test''', 'com.teradata.jdbc.TeraDriver', 'Teradata 8/9 (JDBC) gen', 'CAST({0} AS CHAR(255))');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (12,  'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE  TABLE_TYPE = ''BASE TABLE'' order by TABLE_SCHEMA;', 'com.microsoft.sqlserver.jdbc.SQLServerDriver', 'SQLServer2012', 'CAST({0} AS VARCHAR)');
INSERT INTO connection_types_gdma2(id, select_get_tables, connection_class, name, cast_column_for_search) VALUES (13,  'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES;', 'com.microsoft.sqlserver.jdbc.SQLServerDriver', 'MS SQL Server (JDBC) Full', 'CAST({0} AS VARCHAR)');


SELECT setval('seq_connection_types_gdma2', (SELECT MAX(id) FROM connection_types_gdma2));



--------- INSERT SCRIPTS TO INITIALIZE DATABASE - MS SQL SERVER --------
		   
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SHOW TABLES', 'com.mysql.jdbc.Driver', 'MySQL (JDBC)', 'CAST({0} AS CHAR)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('select table_schema||''.''||table_name as table_name from information_schema.tables where table_schema not in (''pg_catalog'', ''information_schema'') order by table_schema||''.''||table_name', 'org.postgresql.Driver', 'Postgres 9.6.2 JDBC', 'CAST({0} AS VARCHAR)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE= ''U'' ORDER BY NAME', 'sun.jdbc.odbc.JdbcOdbcDriver', 'MS SQL Server (ODBC)', 'CAST({0} AS VARCHAR)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('select table_name as TABLE_NAME from user_tables', 'sun.jdbc.odbc.JdbcOdbcDriver', 'Oracle 8/9 (ODBC)', 'CAST({0} AS VARCHAR2)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('select table_name as TABLE_NAME from user_tables', 'oracle.jdbc.OracleDriver', 'Oracle 8/9 (JDBC)', 'CAST({0} AS VARCHA2)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT TABLENAME AS TABLE_NAME FROM DBC.TABLES ORDER BY TABLENAME', 'sun.jdbc.odbc.JdbcOdbcDriver', 'Teradata 8/9 (ODBC)', 'CAST({0} AS CHAR(255))')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT TABLENAME AS TABLE_NAME FROM DBC.TABLES ORDER BY TABLENAME where databasename = ''financial''', 'com.teradata.jdbc.TeraDriver', 'Teradata 8/9 (JDBC)', 'CAST({0} AS CHAR(255))')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE=''U'' ORDER BY NAME', 'net.sourceforge.jtds.jdbc.Driver', 'MS SQL Server (JDBC)', 'CAST({0} AS VARCHAR)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE=''V'' ORDER BY NAME', 'net.sourceforge.jtds.jdbc.Driver', 'MS SQL Server (JDBC)(Views)', 'CAST({0} AS VARCHAR)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT NAME as TABLE_NAME FROM SYSOBJECTS WHERE XTYPE IN (''U'', ''V'') ORDER BY NAME', 'net.sourceforge.jtds.jdbc.Driver', 'MS SQL Server (JDBC)(Both)', 'CAST({0} AS VARCHAR)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT TABLENAME AS TABLE_NAME FROM DBC.TABLES ORDER BY TABLENAME where databasename = ''gdma_test''', 'com.teradata.jdbc.TeraDriver', 'Teradata 8/9 (JDBC) gen', 'CAST({0} AS CHAR(255))')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = ''BASE TABLE'' order by TABLE_SCHEMA;', 'com.microsoft.sqlserver.jdbc.SQLServerDriver', 'SQLServer2012', 'CAST({0} AS VARCHAR)')
--INSERT INTO [dbo].[connection_types_gdma2] ( [select_get_tables] ,[connection_class] ,[name] ,[cast_column_for_search] ) VALUES ('SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES;', 'com.microsoft.sqlserver.jdbc.SQLServerDriver', 'MS SQL Server (JDBC) Full', 'CAST({0} AS VARCHAR)')
